### PR TITLE
Migrate to llama-index 0.10.0+

### LINKED ISSUE #162: Update Reginald with new llama-index
llama-index has been fully restructured as of v.0.10.0.
[llama-hub](https://github.com/run-llama/llama-hub) has now been deprecated and merged into the llama-index repo.

Migration guide is [here](https://docs.llamaindex.ai/en/stable/getting_started/v0_10_0_migration.html)

We should update Reginald with these changes!

### PR DESCRIPTION
**Pull request by rwood-97**
Updating to new llama-index

Fixes #162 

Notes:
- I've used legacy for the `messages_to_prompt` and `completion_to_prompt` import. Potentially we should update but I can't find the `completion_to_prompt` in the new llama-index. Maybe [here](https://github.com/run-llama/llama_index/blob/2ebdb23630347876e2915cffb338fc1d17b4439f/llama-index-core/llama_index/core/base/llms/generic_utils.py) or [here](https://github.com/run-llama/llama_index/blob/2ebdb23630347876e2915cffb338fc1d17b4439f/llama-index-integrations/llms/llama-index-llms-llama-cpp/llama_index/llms/llama_cpp/base.py#L22C1-L25C2) is relevant.
- I'm returning `Settings` in `setup_settings` but I don't really know if I need to do this.

### CODE REVIEW

**Comment by rchan26** [comment]
thanks @rwood-97! I updated a few of the other libraries and I think this largely works now. There were a few issues with like setting up the tokenizers for each model and also your comment about using `legacy` code from the `llama_index` library which I've fixed.

as discussed on Slack, we'll port over that code as we can customise it for different models we might use and just in case llama-index drops this in the future. it would be good to have an easy way for us to pass in prompt templates and different ways to construct prompts, as I think that's actually why we weren't successful with using the Huggingface models previously as we just didn't configure them properly (I think)

can you have a last check over please and we can merge?

**Review by rchan26 — APPROVED** [review]

**Comment by rwood-97** [comment]
```
...
OSError: You are trying to access a gated repo.
Make sure to request access at https://huggingface.co/meta-llama/Llama-2-7b-chat-hf and pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`.
```

Just logging this error incase we need to address it

**Comment by rwood-97** [comment]
Okay all good :)

**Comment by rchan26** [comment]
ah yeah, this is a good spot @rwood-97. I added a line in there to load in the tokenizer for Llama2 which needs requesting. I think we would need to maybe add a line to load in a environment variable for a `HUGGINGFACE_TOKEN`. we would need that also for the Huggingface model as well if the user ever wanted to use a gated model that required some sort of access first like Llama or Gemma. I'll make a quick issue

**Pull request merged**
